name: CI - Build Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo files (debug)
        run: |
          pwd
          ls -la
          echo "git files:"
          git ls-files
          echo "requirements size:"
          ls -l requirements.txt || true

      # ---- Authenticate to Google Cloud using the service account key secret ----
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 471.0.0'

      - name: Auth with service account key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Verify gcloud access (read-only)
        run: |
          gcloud --version
          echo "Project: ${GCP_PROJECT_ID}  Region: ${GCP_REGION}"
          gcloud config set project "${GCP_PROJECT_ID}"
          # list enabled services just to prove auth works (safe read-only)
          gcloud services list --enabled --format="table(config.name)"
        shell: bash

      # ---- Docker Build (local check only; no push yet) ----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/vertex-feature:ci