name: CI - Build & Push Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      AR_REPO: ${{ vars.AR_REPO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---- Authenticate with service account ----
      - name: Auth with service account key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 471.0.0'

      # ---- Configure Docker to use gcloud as a credential helper ----
      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker "${{ env.GCP_REGION }}-docker.pkg.dev" --quiet
        shell: bash

      # (Optional) quick debug to confirm envs
      - name: Show env values (masked in logs)
        run: |
          echo "Project: ${{ env.GCP_PROJECT_ID }}"
          echo "Region:  ${{ env.GCP_REGION }}"
          echo "Repo:    ${{ env.AR_REPO }}"
        shell: bash

      # ---- Build and Push Docker Image ----
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/vertex-feature:latest
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/vertex-feature:${{ github.sha }}